### ISSUE TITLE
ModuleBuildError: Module build failed: ReferenceError: [BABEL]

### ISSUE THREAD

**Issue by dmitriz** [tomastrajan/component-pattern-for-angular-js-1-x#2]
Just tried to run `npm run build` and getting these errors:

``` sh
$ npm run build

> component-pattern-for-angular-js-1-x@1.0.0 build /Users/dmitrizaitsev/Repos/component-pattern-for-angular-js-1-x
> webpack --config webpack.build.js --bail -p

ModuleBuildError: Module build failed: ReferenceError: [BABEL] /Users/dmitrizaitsev/Repos/component-pattern-for-angular-js-1-x/src/app.js: 
Unknown option: /Users/dmitrizaitsev/Repos/.babelrc.presets
```

**Comment by tomastrajan** [comment]
I suppose this is caused by `^` in version specification in `package.json` with newer version not being compatibile, quick fix would be to remove all `^` singns, deleting `node_modules` and running `npm i` again.

That being said I / you may look into it and upgrade this example to use new babel 6.

**Comment by tomastrajan** [comment]
Used exact versions in `package.json` to make sure is runnable from fresh install.

**Comment by dmitriz** [comment]
Tried with the new update but sadly the same error. :(
Thanks for it anyway!
I see you are referring to the newer package, so will try that instead.

**Comment by tomastrajan** [comment]
Hmm have you deleted your original `node_modules` folder ? I tried fresh install with this updated and it worked ?

**Comment by tomastrajan** [comment]
Tried it again, fresh clone & install and works

**Comment by dmitriz** [comment]
Is there any damn presets settings to be manually added?

**Comment by tomastrajan** [comment]
Not for Babel5, only for Babel 6+

**Comment by dmitriz** [comment]
But we have this problem even with 5, so they must be breaking something, I'm really tired of them :(
